CREATE TABLE IF NOT EXISTS settings (id INTEGER PRIMARY KEY CHECK(id=1), enabled INTEGER NOT NULL DEFAULT 1, watchlist TEXT NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS alerts (id TEXT PRIMARY KEY, generation INTEGER NOT NULL, payload TEXT NOT NULL, triggered_at INTEGER, triggered_price REAL);
CREATE TABLE IF NOT EXISTS runtime (id INTEGER PRIMARY KEY CHECK(id=1), last_started INTEGER, last_finished INTEGER, report TEXT, lease_until INTEGER NOT NULL DEFAULT 0);
INSERT OR IGNORE INTO settings VALUES (1, 1, '["BTC-USDT","ETH-USDT","SOL-USDT","NVDA","AAPL","TSLA","600519.SS","0700.HK"]', 0);
INSERT OR IGNORE INTO runtime (id,lease_until) VALUES (1,0);
